name: My First Pipeline

on:
 push:
   branches: ["main"]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Updating Linux Packages
      run: sudo apt update

    - run: |
         sudo apt install nginx
         sudo systemctl enable nginx
         sudo systemctl restart nginx
         sudo systemctl status nginx
         cd /etc/nginx/sites-available
         ls 
         
    

    

  
